### ISSUE TITLE
Footnote number not really a superscript

### ISSUE THREAD

**Issue by legends2k** [steinvc/holo-alfa#3]
The footnote number<sup>1</sup> next to the text, although is wrapped within the `<sup> ... </sup>` tags doesn't really appear as a superscript. This is due to `reset.css` having selectors `a` and `sup` with properties 

```
font: inherit;
vertical-align: baseline;
```

I've fixed it by removing the `sup` and `sub` selectors and changing `a` to `a:not(.footnote)`. If that's OK, I can issue a pull request.

**Comment by stijnvc** [comment]
Thanks for reporting this. You're more than welcome to issue a pull request.
